spring.application.name=srv

# Pinduoduo Duoduo Ke demo credentials
pdd.client-id=de78e789550342468e2229ca20b3c3a3
pdd.client-secret=73193ee64bba8e72230fe7ad36db01298349566e
pdd.host=https://gw-api.pinduoduo.com/api/router
pdd.version=V1
